name: hrrrcast-live
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - joblib
  - matplotlib
  - xarray
  - dask
  - seaborn
  - fire
  - xesmf
  - netcdf4
  - h5netcdf
  - bottleneck
  - cartopy
  - tqdm
  - pandas
  - zarr
  - pygrib
  - tensorflow==2.15.0
